port = 6687

allow_origin = ["*"]

api_key = "helloworld"
tg_key = "123456789:AAHEUURbcdefghijklmn123opqrstuvwxyz"
# The manager will watch the workers once in every `monitor_interval` seconds,
# An alarm will be set off if a worker haven't heartbeat in the past `heartbeat_alarm_val` seconds.
heartbeat_alarm_val = 60
monitor_interval = 30
manager_name = "NyaM"

db_name = "ssmonitor"
db_user = "root"
db_pass = ""
db_charset = "utf8mb4,utf8"
db_collation = "utf8mb4_unicode_ci"

session_lifetime = 3600

# Will manager create tasks on a daily schedule?
manager_schedule = true
# Minutes
manager_interval = 60

[[admin]]
username = "root"
password = "root"

[friendly]
worker = "员工"
watcher = "观察者"
tester = "测试员"
ipv4tester = "IPv4测试员"
ipv6tester = "IPv6测试员"
cleaner = "清洁工"
manager = "经理"
broadcaster = "广播姬"